
#Para que si ha ocurrido un error, capture el error y no pare la ejecucion del programa
#Programacion defensiva
try:
    print(x)
except:
    print("ha ocurrido algun error")
